version: '3.9'

services:
  userManagementDB:
    image: postgres:latest
    ports:
      - "5433:5432"
    networks:
      - spring-postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: userManagementDB
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always

networks:
  spring-postgres-network:
    driver: bridge

volumes:
  postgres-data: